version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 10000
      runas: root
  ApplicationStart:
    - location: scripts/startbot.sh
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: scripts/stopbot.sh
      timeout: 20000
      runas: root

